language: node_js
node_js:
- '8'
- '10'
- '11'
- '12'
script: node run_tests.js
notifications:
  email: false
  irc:
  - irc.freenode.org#statsd
deploy:
  provider: npm
  email: elliot@lybrary.io
  api_key:
    secure: deHm/dx0AJoSpkgbi+480BbC8Qxsv5vf4TPfMqM8uGYicj6qMJBjG7AZtCUIcJ0mSEoc9Zf79jOJCeWC53CWziQX+D+AXDC/8RGlqtx1h1zgpM6m1NonceqUt9wN/tVG1eNa/22WrerMA3F2rxo5QtY3rMxGMlJjCYOwyFR++eM=
  on:
    tags: true
    repo: statsd/statsd
